#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

function usage() {
  console.error("usage: bson-codegen.mjs [--check] schema.json output.mbt");
  process.exit(2);
}

const args = process.argv.slice(2);
const check = args[0] === "--check";
if (check) args.shift();
if (args.length !== 2) usage();

const [schemaPath, outputPath] = args;
const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
const identifier = /^[A-Z][A-Za-z0-9_]*$/;
const fieldIdentifier = /^[a-z][A-Za-z0-9_]*$/;
if (!Array.isArray(schema.types) || schema.types.length === 0) {
  throw new Error("schema.types must be a non-empty array");
}

function quote(value) {
  return JSON.stringify(value);
}

function validateType(type, context) {
  if (typeof type !== "string" || !/^[A-Za-z][A-Za-z0-9_]*(?:\[[A-Za-z0-9_, ?]+\])?[?]?$/.test(type)) {
    throw new Error(`${context}: invalid MoonBit type ${type}`);
  }
}

const lines = [
  "// Generated by tools/bson-codegen.mjs. Do not edit.",
  "// The source schema is checked into codegen/.",
  "",
];

for (const type of schema.types) {
  if (!type || !identifier.test(type.name)) {
    throw new Error("each type.name must be a PascalCase identifier");
  }
  if (!Array.isArray(type.fields) || type.fields.length === 0) {
    throw new Error(`${type.name}: fields must be a non-empty array`);
  }
  const seen = new Set();
  for (const field of type.fields) {
    if (!field || !fieldIdentifier.test(field.name) || seen.has(field.name)) {
      throw new Error(`${type.name}: invalid or duplicate field ${field?.name}`);
    }
    seen.add(field.name);
    const wireName = field.rename ?? field.name;
    if (typeof wireName !== "string" || wireName.includes("\0")) {
      throw new Error(`${type.name}.${field.name}: invalid BSON field name`);
    }
    validateType(field.type, `${type.name}.${field.name}`);
    if (field.optional === true && field.type.endsWith("?")) {
      throw new Error(`${type.name}.${field.name}: optional fields must not repeat '?'`);
    }
  }

  lines.push("///|");
  lines.push(`pub impl ToBson for ${type.name} with fn to_bson(self) {`);
  lines.push("  Document(");
  lines.push("    Document::new()");
  for (const [index, field] of type.fields.entries()) {
    const wireName = field.rename ?? field.name;
    const suffix = index === type.fields.length - 1 ? "," : "";
    lines.push(`    .set(${quote(wireName)}, to_bson(self.${field.name}))${suffix}`);
  }
  lines.push("  )");
  lines.push("}");
  lines.push("");
  lines.push("///|");
  lines.push(`pub impl FromBson for ${type.name} with fn from_bson(value) {`);
  lines.push("  let document = Document::from_bson(value)");
  lines.push("  {");
  for (const field of type.fields) {
    const wireName = field.rename ?? field.name;
    if (field.optional === true) {
      lines.push(
        `    ${field.name}: document.get(${quote(wireName)}).map(value => from_bson(value)),`,
      );
    } else {
      lines.push(
        `    ${field.name}: from_bson(document.require(${quote(wireName)})),`,
      );
    }
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

const generated = `${lines.join("\n").trimEnd()}\n`;
if (check) {
  const current = fs.readFileSync(outputPath, "utf8");
  if (current !== generated) {
    console.error(`generated output is stale: ${path.relative(process.cwd(), outputPath)}`);
    process.exit(1);
  }
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, generated);
}
